### ISSUE TITLE
Version mismatch for jammy debs due to failed build workflow

### ISSUE THREAD

**Issue by aptalca** [jellyfin/jellyfin-packaging#19]
Just a heads up.

It looks like the noble build failed, and as a result, other active builds were canceled by Github: https://github.com/jellyfin/jellyfin-packaging/actions/runs/8873575844/job/24359629418

At the time of the failure, amd64 debs for jammy were already pushed, but arm debs were not, resulting in different versions being offered for nightly on amd64 vs arm64.

**Comment by joshuaboniface** [comment]
Indeed, seems it failed due to a bug that's been fixed, and I've just added another tweak to prevent it from reoccurring. We're just triggering another workflow unstable now.
