### ISSUE TITLE
Tags corresponding to the release tags of the server/web repos

### ISSUE THREAD

**Issue by mrblumi** [jellyfin/jellyfin-packaging#22]
Would it be possible to provide release tags (or even better versioned tarballs) in this repository? That would make it a lot easier for package maintainers of other distros than debian to figure out what commit here belongs to the release tarballs in the server/web repos.

Or am I missing some easy way? I would like to avoid to have to clone this whole repo including all the other repos as submodules in oder to have a consistent state all over server, web, systemd files, config, etc when nearly everything I need is provided as versioned tarball

**Comment by joshuaboniface** [comment]
I'm not sure I understand the goal of this. This repository is basically a template and set of scripts for generating releases from the main code repos at a particular time. What's in here isn't tied in any way to the actual releases of Jellyfin.

**Comment by joshuaboniface** [comment]
So what I mean is, our goal here is that if something packaging related changes, it changes for everything built going forward. To use the example of the systemd unit, if we update that, then all of a current-stable-release rebuild, the next stable release, the next unstable, etc. would all get that change. Or are you requesting that, after we put out a release, we put a tag in here for historical reasons?

**Comment by mrblumi** [comment]
Yes, but that is IMHO exactly an issue.

In Arch Linux for example I want to generate reproducible builds. If I rebuild the exakt same package version a few months later that package could be different than the one from before even if I use the exakt same build script. And I am convinced that Arch won't be the only distribution doing it in similar ways.

Thus something like a release tag or tarball (IMHO better because the build scripts do not have to depend on git than) would be a huge benefit. 

* no I am not the package maintainer there, I am just strugling to get Jellyfin updated to the latest version :)

**Comment by joshuaboniface** [comment]
I can certainly have the packaging repo generate a release (which would include the tarball) as part of the release process. I'm going to add that to our release system.

**Comment by mrblumi** [comment]
Thanks for clarifying this. I completely understand your point of view. I just didn’t realize that it was not intended for public use (maybe I have missed that)… But If you‘d ask me, (leaving out the fact that the repo is only for you) I‘d prefer a tag matching the jellyfin-server/-web version tag. That would make it easier going back in time and make a match between the server, web and build-tools versions.

I am currently trying to rebuild the Arch package on my own, cause the upstream package is still on 10.8.x and based on the upstream PKGBUILD of Arch I had a bit of a time until i figured out, that the environment file and the systemd unit file disappeared in the 10.9.x repos. What came nearest to something provided by the Jellyfin team were these files in this very repo here to use.

I already thought about just using custom written env and unit files, but I think using these files here and just patching them with my distro specific adjustments would be somehow better because I stay closer your upstream changes…

**Comment by mrblumi** [comment]
My first idea was to clone the repo via the build script leaving out the submodules and only pick the files of interest out of the debian conf folder and maybe apply some arch specific patches on them. But all of that would be completely automated inside the PKGBUILD script.

**Comment by joshuaboniface** [comment]
>I am currently trying to rebuild the Arch package on my own, cause the upstream package is still on 10.8.x and based on the upstream PKGBUILD of Arch I had a bit of a time until i figured out, that the environment file and the systemd unit file disappeared in the 10.9.x repos. What came nearest to something provided by the Jellyfin team were these files in this very repo here to use.

Indeed, the files were moved here from the main repos :-)

>I already thought about just using custom written env and unit files, but I think using these files here and just patching them with my distro specific adjustments would be somehow better because I stay closer to your upstream changes…

Fair point, and helps ensure consistency between platforms.

>My first idea was to clone the repo via the build script leaving out the submodules and only pick the files of interest out of the debian conf folder and maybe apply some arch specific patches on them. But all of that would be completely automated inside the PKGBUILD script.

Makes sense to me.

>I‘d prefer a tag matching the jellyfin-server/-web version tag. 

OK, I'll do so!

If we do need to update a package and rebuild, we'll have to find a clean way to handle it. My first thought would be to use a dated suffix (`-202405170000`, `-202405180000`, etc.) to future rebuilds, but I'm not sure if `PKGBUILD` can handle that. We could also retag the version, but that sort of defeats the purpose. I'm curious what you think would be ideal here!

**Comment by joshuaboniface** [comment]
OK great, dated suffixes are ideal then. So we'd have a tag like `v10.9.0-202405170000` in YYYYMMDDHHMM format in this repo, and then if a change + rebuild is needed, an updated date will be tagged.

**Comment by joshuaboniface** [comment]
Should be active now and going forward.

**Comment by mrblumi** [comment]
Thanks
