### ISSUE TITLE
Requirements missing/wrong 

### ISSUE THREAD

**Issue by gurka** [jellyfin/jellyfin-packaging#27]
Trying to build jellyfin for the first time and I noticed a few things:

- `requirements.txt` has the wrong package name for the python git library. `git` is not available in PyPI, but `GitPython` is, which seems to be the correct package (based on Debian's package [python3-git](https://neuro.debian.net/pkgs/python3-git.html), which links to [GitPython on Github](https://github.com/gitpython-developers/GitPython), which links to [GitPython on PyPI](https://pypi.org/project/GitPython/)).
- `README.md` should maybe mention that `docker-buildx-plugin` is required for the docker build

**Comment by joshuaboniface** [comment]
Good finds, let me update both.
