### ISSUE TITLE
[Docker] Multiple tag levels?

### ISSUE THREAD

**Issue by Strit** [jellyfin/jellyfin-packaging#29]
Currently there is only `latest` and `complete_version` as docker tags. Which is great.

But to not have to edit my docker compose each  release, is it possible to add `Major.Minor` and even just `Major` version number tags?

Meaning, that tag `10.9.5`, `10.9` and `10` would all point to the same docker image as long as `10.9.5` is the latest one and it would update `10.9` and `10` tags when it gets updates to `10.9.6`.

That way, people can define the Major.Minor version number in their compose file and have automations update them.

**Comment by joshuaboniface** [comment]
That is a very good idea and definitely doable. I'll look at implementing that now for our next point release.
