### ISSUE TITLE
Package for Ubuntu - unmet dependencies to jellfin-ffmpeg5

### ISSUE THREAD

**Issue by BaumiCoder** [jellyfin/jellyfin-packaging#7]
I tried to install jellyfin on a virtual machine (VirtualBox) with Ubuntu 22.04.4 LTS jammy. I run the command that is mentioned in the [download section](https://jellyfin.org/downloads/server) of the website:
```bash
curl https://repo.jellyfin.org/install-debuntu.sh | sudo bash
```
This leads to an error, because of a missing dependency:
```bash
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 jellyfin : Depends: jellyfin-ffmpeg5 (>= 5.0.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
ERROR: Faild to install Jellfin. Use https://jellyfin.org/contact to find us for troubleshooting.
```

Is there maybe some bug in the repo, because of recently [released ffmpeg6 for jellyfin](https://github.com/jellyfin/jellyfin-ffmpeg/releases/tag/v6.0.1-2), so that the `jellyfin` package still requires the ffmpeg5 package but these does not exist anymore?

**Comment by joshuaboniface** [comment]
This was a dependency missed in the repo while cutting over the repo. It *should* be corrected at this point but if not please let us know.

**Comment by BaumiCoder** [comment]
Thank you, now it works correctly.
